# PyTorch Fundamentals

### Importing the libraries

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cu128


## Introduction to Tensors

### **Creating tensors**
PyTorch tensors are crated using `torch.Tensor()` = https://docs.pytorch.org/docs/stable/tensors.html

#### **Scalar**

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensors as back as python int
scalar.item()

7

#### **Vector**

In [6]:
vector = torch.Tensor([7, 7])
vector

tensor([7., 7.])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

#### **MATRIX**

In [9]:
MATRIX = torch.Tensor([[7, 8], [9, 8]])
MATRIX

tensor([[7., 8.],
        [9., 8.]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([9., 8.])

In [12]:
MATRIX.shape

torch.Size([2, 2])

#### **TENSOR**

In [13]:
scalar.ndim

0

In [14]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0][0]

tensor([1, 2, 3])

### Random tensors
why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random nubmers to better represent  the data.

`Start with random numbers -> Look at data -> Update random numbers -> look at data -> update random numbers`

Torch random tensors - https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [18]:
# Create a random number tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9255, 0.7420, 0.7727, 0.0787],
        [0.8127, 0.6663, 0.8901, 0.3520],
        [0.9276, 0.3021, 0.8491, 0.7815]])

In [19]:
random_tensor.ndim

2

In [20]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [21]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [24]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
**Note:** Tensor datatype is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Single-precision_floating-point_format

In [26]:
# Float 32 tensor
float_32__tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None, # What datatype is tensor (eg: float32 or float16)
                                device=None, # What device is your tensor on
                                requires_grad=False) # whether or not to track gradients with this tensors operations


float_32__tensor

tensor([3., 6., 9.])

In [27]:
float_32__tensor.dtype

torch.float32

In [28]:
float_16_tensor = float_32__tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
float_16_tensor * float_32__tensor

tensor([ 9., 36., 81.])

In [30]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [31]:
float_32__tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)
1. Tensors not right datatype - to do get datatype from a tensor, can you use `tensor.dtype`
2. Tensors not right shape - to get shape from tensor , can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [32]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.5351, 0.3677, 0.2665, 0.6018],
        [0.8985, 0.1428, 0.9704, 0.5055],
        [0.9990, 0.5562, 0.2966, 0.0719]])

In [33]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.5351, 0.3677, 0.2665, 0.6018],
        [0.8985, 0.1428, 0.9704, 0.5055],
        [0.9990, 0.5562, 0.2966, 0.0719]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor Operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication


In [34]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [35]:
# Multiply tensor by 10
tensor = tensor * 10

In [36]:
tensor

tensor([10, 20, 30])

In [37]:
# Subtract 10
tensor - 10

tensor([ 0, 10, 20])

In [38]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([100, 200, 300])

### Matrix Multiplication

Two main ways of performing matrix multiplication in neural network and deep learning:
1. Element wise multiplication
2. Matrix Multiplication

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimension** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [39]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals: tensor([100, 400, 900])


In [40]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(1400)

In [41]:
# Matrix Multiplication by hand

1 * 1 + 2*2 + 3*3

14

In [42]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(1400)
CPU times: user 0 ns, sys: 1.88 ms, total: 1.88 ms
Wall time: 1.22 ms


In [43]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 265 μs, sys: 82 μs, total: 347 μs
Wall time: 265 μs


tensor(1400)

### One of the most common errors in deep learning: shape errors

In [44]:

# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])
 
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9 ,12]])
# torch.mm(tensor_A, tensor_B) # torch.mm is same as torch.matmul (it's alias for writing less code)
torch.matmul(tensor_A, tensor_B)



RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

### To fix our tensor shape error issues, we can manipulate the shape of one of our tensor using a **transpose**.

A **Transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
# Transpose
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed 
print(f"Original shape: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shape: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print(f"Output\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shape: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shape: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggeration)

In [ ]:
# Create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
# Find the mean 
#! NOTE: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Find the positional min and max

In [ ]:
# Find the position in tensor that has minimum value with argmin() -> returns index position of target tensor where minimum value occurs
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original 
tensor
* Stacking - combine multiple tenors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add `1` dimensional to a target tensor
* Permute - Return a view of the input with dimensional permuted (swaped) in certain way.

In [ ]:
#  Let's create a tenor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a veiw of tensor shares the same memmory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# Squeeze
# torch.squeeze() - removes all single dimensional from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Removes extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
## Unsqueeze
# torch.unsqueeze() - adds a single dimensional to a target tensor at a specific dim (dimension)

print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [50]:
# Permute
# torch.permute - rearrange the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0
print(f"Previous shape: {x_original.shape}") 
print(f"New shape: {x_permuted.shape}") # [color_change, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [57]:
x_original[0, 0, 0] = 7228219
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(7228219.), tensor(7228219.))

## Indexing (selecting data from tensors)
Indexing with PyTorch is similar to indexing with NumPy.

In [59]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [65]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [66]:
# Let's index on the most inner bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [77]:
# Let's index on the most inner bracket (last dimension)
x[0][2][2]

tensor(9)

In [78]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [79]:
# Get all value of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [80]:
# Get all values of the 0 dim but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [84]:
# Index on x to return 9
print(x[:, 2, 2])

# Index on x to return 3, 6, 9
print(x[:, :, 2])

tensor([9])
tensor([[3, 6, 9]])


## PyTorch tensors & NumPy
Numpy is powerful scientific Python numerical computing library.
And because of this PyTorch has functionality to interact with it.
* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [87]:
# NumPy array to tensor
array = np.arange(1.0, 8.0)
#! Warning: when converting from NumPy  -> PyTroch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
tensor = torch.from_numpy(array) 
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [88]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [90]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [91]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)
In short hwo a nerual network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of data -> again -> again -> again.......

To reduce the randomness in neural network and PyTorch comes the concept of a random **random seed**.

Essentially what the random seed does is "flavor" the randomness.

In [94]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)

print(random_tensor_A == random_tensor_B)

tensor([[0.3126, 0.7032, 0.3552, 0.7573],
        [0.7235, 0.8221, 0.0346, 0.0233],
        [0.8278, 0.2643, 0.8261, 0.1243]])
tensor([[0.5715, 0.0508, 0.7187, 0.1361],
        [0.6597, 0.5743, 0.3274, 0.1843],
        [0.3426, 0.8038, 0.8822, 0.9959]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [96]:
# Let's make some random but reproducible tensors
# set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility:
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Running tensors and PyTorch objects on GPUs (and making faster computations)
GPUs =faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory(good)

### 1. Getting a GPU
1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU.
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally

### 2. Check for GPU access with PyTorch

In [102]:
# Cehck for GPU access with PyTorch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, its best practice to setup device agnostic code:
https://pytorch.org/docs/stable/notes/cuda.html#best-practice

E.g. run on GPU if available, else default to CPU

In [103]:
# Setup device agnostic code
device  = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [104]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [106]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [107]:
# Move tensors to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [109]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [110]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu[Theme]
Current=maldives

tensor([1, 2, 3], device='cuda:0')