# PyTorch Fundamentals

### Importing the libraries

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cu128


## Introduction to Tensors

### **Creating tensors**
PyTorch tensors are crated using `torch.Tensor()` = https://docs.pytorch.org/docs/stable/tensors.html

#### **Scalar**

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensors as back as python int
scalar.item()

7

#### **Vector**

In [5]:
vector = torch.Tensor([7, 7])
vector

tensor([7., 7.])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

#### **MATRIX**

In [8]:
MATRIX = torch.Tensor([[7, 8], [9, 8]])
MATRIX

tensor([[7., 8.],
        [9., 8.]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([9., 8.])

In [11]:
MATRIX.shape

torch.Size([2, 2])

#### **TENSOR**

In [12]:
scalar.ndim

0

In [13]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0][0]

tensor([1, 2, 3])

### Random tensors
why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random nubmers to better represent  the data.

`Start with random numbers -> Look at data -> Update random numbers -> look at data -> update random numbers`

Torch random tensors - https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [17]:
# Create a random number tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1578, 0.4677, 0.5659, 0.9190],
        [0.8440, 0.9343, 0.0013, 0.6990],
        [0.6503, 0.4734, 0.8126, 0.0342]])

In [18]:
random_tensor.ndim

2

In [19]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [20]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [23]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
**Note:** Tensor datatype is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Single-precision_floating-point_format

In [25]:
# Float 32 tensor
float_32__tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None, # What datatype is tensor (eg: float32 or float16)
                                device=None, # What device is your tensor on
                                requires_grad=False) # whether or not to track gradients with this tensors operations


float_32__tensor

tensor([3., 6., 9.])

In [26]:
float_32__tensor.dtype

torch.float32

In [27]:
float_16_tensor = float_32__tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
float_16_tensor * float_32__tensor

tensor([ 9., 36., 81.])

In [29]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [30]:
float_32__tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)
1. Tensors not right datatype - to do get datatype from a tensor, can you use `tensor.dtype`
2. Tensors not right shape - to get shape from tensor , can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [31]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6048, 0.8847, 0.2846, 0.2276],
        [0.1124, 0.4831, 0.3864, 0.5478],
        [0.2375, 0.4231, 0.7631, 0.9936]])

In [32]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.6048, 0.8847, 0.2846, 0.2276],
        [0.1124, 0.4831, 0.3864, 0.5478],
        [0.2375, 0.4231, 0.7631, 0.9936]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor Operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication


In [45]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [44]:
# Multiply tensor by 10
tensor = tensor * 10

In [48]:
tensor

tensor([1, 2, 3])

In [49]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [51]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication

Two main ways of performing matrix multiplication in neural network and deep learning:
1. Element wise multiplication
2. Matrix Multiplication

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [53]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [55]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [57]:
# Matrix Multiplication by hand

1 * 1 + 2*2 + 3*3

14

In [58]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.35 ms, sys: 5.02 ms, total: 7.37 ms
Wall time: 14.1 ms


In [59]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 403 μs, sys: 78 μs, total: 481 μs
Wall time: 336 μs


tensor(14)